### ISSUE TITLE
Copy the GIF directly to the clipboard

### ISSUE THREAD

**Issue by kejadlen** [kejadlen/giphy.alfredworkflow#2]

**Comment by kejadlen** [comment]
Dun.

**Comment by invious** [comment]
How? I am holding CMD before pressing enter and the gif is not copying to the pasteboard?

**Comment by kejadlen** [comment]
Ah, I screwed it up. New release with the fix: https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v2.0.2

**Comment by invious** [comment]
I saw you changed the filter variable check from {var:copy} to {var:giphy_copy}, that's what i was going to try to see if you had made a mistake. but even with that fix I am having trouble and cannot get it to work. the modifier key is working, because I substituted the script with a notification, but the gif isn't copying to pasteboard

**Comment by kejadlen** [comment]
Ah, I was afraid of that. There should be a binary in the workflow called `imgpbcopy` but I wasn't sure if it would work on other peoples' machines. It takes a path to an image and should put it on the pasteboard. Can you see if running that directly works?

**Comment by invious** [comment]
the binary didn't work but using the swift interpreter did

```
./imgpbcopy icon.png
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/aymon/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.C4B633AD-6EC5-4616-A71C-E9AD1E8D4EAE/./imgpbcopy
  Reason: image not found
Abort trap: 6
Aymons-MacBook-Air:user.workflow.C4B633AD-6EC5-4616-A71C-E9AD1E8D4EAE aymon$ swift imgpbcopy.swift icon.png
Aymons-MacBook-Air:user.workflow.C4B633AD-6EC5-4616-A71C-E9AD1E8D4EAE aymon$
```

**Comment by kejadlen** [comment]
You can probably compile the Swift script yourself to make it work, but I don't know how to distribute it to work for everyone, so... ¯_(ツ)_/¯

**Comment by invious** [comment]
Yeah, dunno. I didn't compile it I just changed it to run the script with the interpreter

**Comment by kejadlen** [comment]
Maybe I'll switch it to that for now, thanks for the update.

**Comment by kejadlen** [comment]
Re-opening to figure out a way to make this actually work.

**Comment by invious** [comment]
when I got it to work the script was only copying the image to the NSPasteBoard as PNG, (not animated GIF) so yeah

**Comment by kejadlen** [comment]
@invious I saw that you forked the workflow - does [paste.swift](https://github.com/invious/giphyPaste.alfredworkflow/blob/master/paste.swift) work? I couldn't get that to work.

It would probably help if I knew how to copy an animated gif to the clipboard just in general...

**Comment by invious** [comment]
@kejadlen it used to work! some update must have broken my code. the date of those releases, the code was working. I remember looking far and wide for pasting gif to the keyboard, i can try to look again. Maybe there are some hints in my broken code.

**Comment by invious** [comment]
@kejadlen I think I fixed it! Takes the url as an argument.

```
import Cocoa

var url_arg = CommandLine.arguments[1]

var pb = NSPasteboard(name: NSGeneralPboard)

if let url = NSURL(string: url_arg) {
    if let data = NSData(contentsOf: url as URL) {
        var image =  NSImage(data: data as Data)
        let fileName = url.lastPathComponent
        var saveURL = NSURL(string: "file://" + NSTemporaryDirectory())
        saveURL = saveURL?.appendingPathComponent(fileName!) as NSURL?
        let data = NSData(contentsOf: url as URL)
        data?.write(to: saveURL! as URL, atomically: true)

        pb.declareTypes([NSFilenamesPboardType], owner: nil)
        pb.writeObjects([saveURL!])

    }
}
```

**Comment by kejadlen** [comment]
@invious What OS and version of Swift are you using? This is what I'm trying, which should be pretty much the same as what you're doing, but it's not working for me:

```swift
let pasteboard = NSPasteboard.general()
pasteboard.clearContents()
pasteboard.declareTypes([NSFilenamesPboardType], owner: nil)
let url = URL(fileURLWithPath: "/absolute/path/to/gif.gif")
pasteboard.writeObjects([url as NSPasteboardWriting])
```

When I paste this, I still get a still image.

**Comment by invious** [comment]
Xcode 8, Swift 3.0.1 I don't know but the code I pasted works. Here is my working workflow: https://cl.ly/2T2m1E0m3l0y

**Comment by invious** [comment]
Did it work for you?

**Comment by kejadlen** [comment]
Gave it a shot, but it doesn't work for me.

**Comment by mlaurel** [comment]
Works for me... just so people know, these are the steps I'm doing... 

1.  Initiate Alfred
2.  Type giphy and search parameter, i.e.  "giphy beer"
3.  When you get a list of results in Alfred, use your arrow keys to arrow down to the one you want
4.  DON'T PRESS ENTER... instead, with the list item highlighted, do a CMD+C
5.  Paste in your app

**Comment by invious** [comment]
Which worked, kejadlen's fork or mine?

**Comment by invious** [comment]
I still can't get this to work?

**Comment by kejadlen** [comment]
Ditto - that only copies the link to the gif for me.

**Comment by aliparr-** [comment]
Hello. I updated the Swift code to Swift 3.

https://gist.github.com/aliparr-/7ac174bb5245950496b8bdfe07e55b15

This works for me.

**Comment by aliparr-** [comment]
Hello. I fixed the swift so that copying works. 
Code is here: 
https://github.com/aliparr-/giphy.alfredworkflow/releases/tag/v3.0.4

**Comment by kejadlen** [comment]
Test: 
![image](https://user-images.githubusercontent.com/8639/31001700-a3e25ede-a49a-11e7-8fb2-129deb2ac6c1.png)

**Comment by invious** [comment]
@aliparr- I just installed your new release, and holding the cmd modifier gives a GIF copied notification but when I paste into iMessage, it just pastes the url. God I swear I got my fork to work at one point. I distinctly remember joyfully pasting Gifs into imessage from alfred >_<

**Comment by kejadlen** [comment]
Tracking some of the research I'm doing:

Copying a GIF from Safari:

```swift
let pb = NSPasteboard.general
let item = pb.pasteboardItems?.first
for type in item!.types {
    print(type.rawValue)
}
```

```
public.tiff
dyn.ah62d4rv4gu8zs3pcnzme2641rf4guzdmsv0gn64uqm10c6xenv61a3k
dyn.ah62d4rv4gu8yc6durvwwaznwmuuha2pxsvw0e55bsmwca7d3sbwu
public.url
public.url-name
public.utf8-plain-text
com.apple.flat-rtfd
com.apple.webarchive
```

I'm able to paste the animated GIF into TextEdit, but it doesn't seem to work for Slack/Chrome.

**Comment by kejadlen** [comment]
Some other notes:

- `clearContents` needs to be called first before writing to the pasteboard.
- `writeObjects` with a class that implements `NSPasteboardWriting` is probably the way to go, if we can identify what type should go on the pasteboard and what format it should be in. This is actually ideal, since then this workflow could in theory support copying URLs/HTML/images in one shot, though there is the open question of whether the URL should be the file URL (for local use) or the web URL (for copying for remote use).

**Comment by aliparr-** [comment]
@invious - That's really weird to me. I have it working perfectly here. Would you mind running the alfred debugger on the script and seeing what it throws up?

**Comment by invious** [comment]
@aliparr- 

```
[2017-10-01 20:27:47][ERROR: action.script] ./imgpbcopy.swift:16:9: error: function 'pb' was used as a property; add () to call it
        pb.declareTypes([NSPasteboard.PasteboardType.fileContents], owner: nil)
        ^
          ()
./imgpbcopy.swift:17:9: error: function 'pb' was used as a property; add () to call it
        pb.writeObjects([saveURL!])
        ^
          ()
```

Swift 3.1

`Welcome to Apple Swift version 3.1 (swiftlang-802.0.53 clang-802.0.42). Type :help for assistance.`

Oh and actually I was wrong about it copying the url, that was the previous thing on my clipboard, so I mistakenly thought it was the result of running the script with the CMD modifier, but nothing gets put on the clipboard despite the notification

**Comment by aliparr-** [comment]
Interesting. I'm running 
Apple Swift version 4.0 (swiftlang-900.0.65 clang-900.0.37)

There are changes to NSPasteboard between xcode releases, so maybe install the latest xcode and try again?

**Comment by kejadlen** [comment]
@aliparr- How are you testing that copying the animated gif works?

**Comment by aliparr-** [comment]
@kejadlen - I can paste it where I want. iMessage, whatsapp, anywhere. It's working 100% for me. Can you try updating Swift and giving my version a go?

**Comment by kejadlen** [comment]
@aliparr- Interesting... can you check to see what the following returns when you do `declareTypes` and then `writeObjects`?

```
let item = pb.pasteboardItems?.first
for type in item!.types {
    print(type.rawValue)
}
```

**Comment by aliparr-** [comment]
I get this sort of thing:
"dyn.ah62d4rv4gu8y60cgrf0gnu5tr34gn5xysrkge55bsmwfk8puqy"

**Comment by kejadlen** [comment]
Did some further digging into this today. Got this to work:

```swift
import Cocoa

let path = CommandLine.arguments[1]
let url = URL(fileURLWithPath: path).absoluteURL as NSURL

let pb = NSPasteboard.general
pb.declareTypes([NSPasteboard.PasteboardType.fileContents], owner: nil)
pb.writeObjects([url])
```

**Comment by kejadlen** [comment]
Okay, new release that hopefully implements direct copying of GIFs: https://github.com/kejadlen/giphy.alfredworkflow/releases/tag/v3.1.1

There is still some odd behavior that I haven't been able to nail down - it seemed like it sometimes only worked after I ran the script from the commandline, so that's something to look out for.

**Comment by olivierlefloch** [comment]
This failed for me because

1. The app `imgpbcopy` was from an unauthorized developer
2. I guess I don't have the Swift runtime?

```
dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/alakazam/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.0F3E13E1-4435-447A-AAE4-D5F376DE070C/imgpbcopy
  Reason: image not found
```

**Comment by kejadlen** [comment]
One thing you can try is compiling `imgpbcopy` yourself in the workflow folder. The behavior is still kind of flaky, but I personally don't use it a whole lot so I haven't done a ton of work on it.

**Comment by heyflorin** [comment]
Fixed it on my end. Here are the issues I found.
1. This version of imgpbcopy has some issues, couldn't even compile it. Downloaded version from here: https://gist.github.com/ibolmo/c08973f5d4534ae2ff13f38e02f9e286 and added to Workflow folder. 
2. Modified final script that called imbpbcopy. Notice the "./" and the new variable call: 
`./imgpbcopy "$giphy_url"`
3. (Optional) Removed final qlmanage view since quick I quick preview every gif before I copy so I don't need to see it again.

Works.

**Comment by invious** [comment]
@florinme do you have a working fork? I couldn't quite follow your instructions. I downloaded, chmoded, and added the imgpbcopy file to my path but you lost me at step 2

**Comment by kejadlen** [comment]
So out of curiousity, what are y’all pasting animated GIFs into?

**Comment by heyflorin** [comment]
> @florinme do you have a working fork? I couldn't quite follow your instructions. I downloaded, chmoded, and added the imgpbcopy file to my path but you lost me at step 2

See my screenshot; that's the script to modify with the code above.
![image](https://user-images.githubusercontent.com/3247722/51931300-4bd5d800-23b1-11e9-9c6b-d2854764d884.png)

![image](https://user-images.githubusercontent.com/3247722/51931333-5f813e80-23b1-11e9-944d-12ea3b0f279f.png)

**Comment by heyflorin** [comment]
> So out of curiousity, what are y’all pasting animated GIFs into?

Apple Messages. Often times I don't have the text field highlighted, and so returning the gif directly didn't work for me, which is why I'd rather control when the output happens.

**Comment by invious** [comment]
I think I had to swap out imgpbcopy binary with one I found in some repo

**Comment by invious** [comment]
> Apple Messages

ditto

**Comment by miguelarios** [comment]
> > @florinme do you have a working fork? I couldn't quite follow your instructions. I downloaded, chmoded, and added the imgpbcopy file to my path but you lost me at step 2
> 
> See my screenshot; that's the script to modify with the code above.
> ![image](https://user-images.githubusercontent.com/3247722/51931300-4bd5d800-23b1-11e9-9c6b-d2854764d884.png)
> 
> ![image](https://user-images.githubusercontent.com/3247722/51931333-5f813e80-23b1-11e9-944d-12ea3b0f279f.png)

I tried what you did but could not get it to work. Out of curiosity the imgpbcopy does work as I ran this via terminal with a Giphy link; however, I noticed that how the Giphy url is copied through this workflow it doesn't work via terminal. For example, this is the url for 'hello world' https://media1.giphy.com/media/lcs5BL0NIM4WMv61a9/giphy.gif?cid=e1bb72ff1e937d0c558ace37ce09ebd2dd622bb6557907b3&rid=giphy.gif. I can't have the gif copy to clipboard via the imgpbcopy unless I remove everything after the '?'.

**Comment by kejadlen** [comment]
It appears to be working for me with what's currently in the workflow (`osascript -e  "set the clipboard to (read (POSIX file \"$alfred_workflow_cache/giphy.gif\") as JPEG picture)"`), FWIW.

**Comment by miguelarios** [comment]
> It appears to be working for me with what's currently in the workflow (`osascript -e "set the clipboard to (read (POSIX file \"$alfred_workflow_cache/giphy.gif\") as JPEG picture)"`), FWIW.

Did you change the imgpbcopy?

**Comment by kejadlen** [comment]
@mar005 I have the relevant portion of `imgpbcopy` inlined in the `Run Script` block, which is how the current release is configured.

**Comment by wilfredwee** [comment]
Do we need the new code from December in order to get copy to work? I'm having trouble actually copying the image myself, pressing enter just shows the qlmanage preview.

Edit: Ah, pressing Cmd + Enter successfully copies the gif. Thanks!

**Comment by aaronvegh** [comment]
I came across this thread while trying to support this feature in my own app. I finally managed it using this code: perhaps you'll be able to benefit?

```
let pb = NSPasteboard.general
        do {
            let fileType = try NSWorkspace.shared.type(ofFile: localPath.path)
            let pasteboardType = NSPasteboard.PasteboardType.init(fileType)
            pb.declareTypes([pasteboardType], owner: nil)
            pb.writeObjects([localPath as NSURL])
        } catch {
            return
        }
```

**Comment by bryanbartow** [comment]
@aaronvegh Are you copying remote gifs from a URL or local files in the bundle? Do you have a more full code sample?

**Comment by aaronvegh** [comment]
In my application's case, I'm copying URLs, but this handles both local and remote URLs. Not sure if this will be helpful for you, but here are two methods from my app that handle copying images that handle the image file in one instance, and the URL in another:

```swift
@IBAction func copyOriginalURL(sender: NSMenuItem) {
        guard let gif = gif,
              let originalURL = gif.url else { return }
        // put it on the clipboard
        let pasteboardItem = NSPasteboardItem()
        pasteboardItem.setString(originalURL, forType: .string)
        
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.writeObjects([pasteboardItem])
    }
    
    @IBAction func copyOriginalImage(sender: NSMenuItem) {
        guard let localPath = localPath else { return }
        
        let pb = NSPasteboard.general
        do {
            let fileType = try NSWorkspace.shared.type(ofFile: localPath.path)
            let pasteboardType = NSPasteboard.PasteboardType.init(fileType)
            pb.declareTypes([pasteboardType], owner: nil)
            pb.clearContents()
            pb.writeObjects([localPath as NSURL])
        } catch {
            return
        }
    }
```

**Comment by bryanbartow** [comment]
@aaronvegh This copies the URL to the clipboard, but not the .gif file itself, right? I'm attempting to copy the .gif from my app and paste directly into another app, i.e. Messages.

**Comment by aaronvegh** [comment]
I find this works to do exactly what you're after. For the "actual file", you're really wanting to put the URL in the pasteboard. In a different part of my app where I have to return an object that conforms to `NSPasteboardWriting` (to support drag 'n' drop), I return an `NSURL` object.

**Comment by bryanbartow** [comment]
@aaronvegh Interesting. When I do this and go to paste in Messages, it just pastes the remote URL of the file.

**Comment by elisavetsky** [comment]
It seems as though what we copy is just a JPEG file, the gif is running fine on my mac when I paste it into iMessage, but when i switch over to my phone's iMessage, it reads as a JPEG picture and doesn't animate. Huh???

**Comment by MrBeardedGuy** [comment]
Just downloaded the latest version and it's sill getting the URL not the actual GIF

**Comment by xeijix** [comment]
FWIW: the applications where I need to be able to paste a gif works if I had a gif on my filesystem and I copied the file through finder via the context menu. 

Since that works, I tried updating the script in the workflow to just set the clipboard to the tmp file (instead of reading it in)

`osascript -e  "set the clipboard to POSIX file \"$alfred_workflow_cache/giphy.gif\""`

And that works for me. YMMV, I didn't test iMessages or other common applications people might use for messaging

**Comment by avoll89** [comment]
I'm having this issue too (@kejadlen I got it to stop crashing! I didn't have python 2 installed 🤦). It only copies a static image.
